apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-secret-reader
  namespace: jenkins
rules:
# Strict access to critical OIDC secret
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames:
    - jenkins-github-oidc-secret
  verbs: ["get"]

# Flexible access for future Jenkins pipeline secrets
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-secret-reader-binding
  namespace: jenkins
subjects:
- kind: ServiceAccount
  name: jenkins-sa
  namespace: jenkins
roleRef:
  kind: Role
  name: jenkins-secret-reader
  apiGroup: rbac.authorization.k8s.io