apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  namespace: jenkins
spec:
  type: ExternalName
  externalName: oauth2-proxy.auth.svc.cluster.local
  ports:
  - port: 4180
    targetPort: 4180