apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-sa
  namespace: auth
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: redis-secret-reader
  namespace: auth
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames:
    - redis-auth-secret
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redis-secret-reader-binding
  namespace: auth
subjects:
- kind: ServiceAccount
  name: redis-sa
  namespace: auth
roleRef:
  kind: Role
  name: redis-secret-reader
  apiGroup: rbac.authorization.k8s.io